import React, { useState, useEffect } from 'react';
import { FileText, Save, CheckCircle2, RotateCcw, Info } from 'lucide-react';

const DEFAULT_TEMPLATE = `<!-- Repo Generated by Github Deploy -->
# {REPO_NAME}

This repository was automatically provisioned.

## Quick Start
1. Clone the repository
2. Install dependencies with \`npm install\`
3. Start the dev server with \`npm run dev\`

## Deployment Link
<!-- DEPLOY_LINK_START -->
No active deployments yet.
<!-- DEPLOY_LINK_END -->
`;

export function ReadmeTemplatePage() {
  const [template, setTemplate] = useState(DEFAULT_TEMPLATE);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const savedTemplate = localStorage.getItem('gitdeploy_readme_template');
    if (savedTemplate) {
      setTemplate(savedTemplate);
    }
  }, []);

  const handleSave = () => {
    localStorage.setItem('gitdeploy_readme_template', template);
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const handleReset = () => {
    if (confirm('Reset to default template?')) {
      setTemplate(DEFAULT_TEMPLATE);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-2">
        <div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            README Template
          </h2>
          <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">
            Configure the default markdown used when initializing new repositories.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleReset}
            className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700 rounded-xl transition-colors flex items-center gap-2 shadow-sm"
          >
            <RotateCcw size={16} /> Reset
          </button>
          <button 
            onClick={handleSave}
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 dark:bg-blue-600 dark:hover:bg-blue-500 rounded-xl transition-all shadow-sm flex items-center gap-2"
          >
            {saved ? <CheckCircle2 size={16} /> : <Save size={16} />}
            {saved ? 'Saved!' : 'Save Changes'}
          </button>
        </div>
      </div>

      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-900/50 rounded-2xl p-4 flex items-start gap-3 text-blue-800 dark:text-blue-200 text-sm">
        <Info size={18} className="shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p><strong>Available Variables:</strong> Use <code className="bg-white/50 dark:bg-black/20 px-1.5 py-0.5 rounded font-mono font-bold text-blue-900 dark:text-blue-100">{"{REPO_NAME}"}</code> to automatically inject the repository name.</p>
          <p><strong>Deployment Tags:</strong> Keep the <code className="bg-white/50 dark:bg-black/20 px-1.5 py-0.5 rounded font-mono font-bold text-blue-900 dark:text-blue-100">&lt;!-- DEPLOY_LINK_START --&gt;</code> and <code className="bg-white/50 dark:bg-black/20 px-1.5 py-0.5 rounded font-mono font-bold text-blue-900 dark:text-blue-100">&lt;!-- DEPLOY_LINK_END --&gt;</code> tags intact to enable automatic Vercel URL injection.</p>
        </div>
      </div>

      <div className="bg-white dark:bg-[#0d1117] rounded-2xl shadow-sm border border-gray-200 dark:border-gray-800 overflow-hidden transition-colors">
        <div className="bg-gray-50 dark:bg-[#161b22] border-b border-gray-200 dark:border-gray-800 px-4 py-3 flex items-center gap-2">
          <FileText size={16} className="text-gray-400" />
          <span className="text-sm font-mono text-gray-600 dark:text-gray-300 font-medium">README.md</span>
        </div>
        <textarea
          value={template}
          onChange={(e) => setTemplate(e.target.value)}
          className="w-full h-[500px] p-6 font-mono text-[13px] leading-relaxed outline-none resize-y bg-transparent text-gray-800 dark:text-gray-200 selection:bg-blue-100 dark:selection:bg-blue-900/50"
          spellCheck="false"
          placeholder="Enter your markdown template here..."
        />
      </div>
    </div>
  );
}
