import React, { useState, useEffect } from 'react';
import { Settings, Github, LayoutGrid, AlertCircle, Plus, Wrench, FileText, Moon, Sun, MonitorSmartphone } from 'lucide-react';
import { TokenManager } from './components/TokenManager';
import { FileExplorer } from './components/FileExplorer';
import { DeployManager } from './components/DeployManager';
import { ReleaseManager } from './components/ReleaseManager';
import { MaintenancePage } from './components/MaintenancePage';
import { ReadmeTemplatePage } from './components/ReadmeTemplatePage';
import { MyApplicationsPage } from './components/MyApplicationsPage';
import { AppTokens, GithubRepo } from './types';
import { getUserRepos, createRepo, createOrUpdateFile, getRepoTree } from './lib/github';

export default function App() {
  const [tokens, setTokens] = useState<AppTokens>({ github: '', vercel: '' });
  const [showTokens, setShowTokens] = useState(false);
  const [currentView, setCurrentView] = useState<'dashboard' | 'maintenance' | 'readme-template' | 'my-applications'>('dashboard');
  const [showMenu, setShowMenu] = useState(false);
  const [darkMode, setDarkMode] = useState(false);
  
  const [repos, setRepos] = useState<GithubRepo[]>([]);
  const [selectedRepo, setSelectedRepo] = useState<string>('');
  const [repoError, setRepoError] = useState<string>('');
  
  const [newRepoName, setNewRepoName] = useState('');
  const [creatingRepo, setCreatingRepo] = useState(false);

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  useEffect(() => {
    const saved = localStorage.getItem('gitdeploy_tokens');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        setTokens(parsed);
      } catch (e) {}
    } else {
      setShowTokens(true);
    }
  }, []);

  useEffect(() => {
    if (tokens.github) {
      setRepoError('');
      getUserRepos(tokens.github)
        .then(setRepos)
        .catch(err => {
          console.error('Failed to load repos:', err);
          setRepoError(err.message || 'Failed to load repositories. Please check your GitHub token.');
          setRepos([]);
        });
    } else {
      setRepos([]);
    }
  }, [tokens.github]);

  const handleCreateRepo = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newRepoName || !tokens.github) return;
    setCreatingRepo(true);
    try {
      const repo = await createRepo(tokens.github, newRepoName);
      setRepos([repo, ...repos]);
      setSelectedRepo(repo.full_name);
      setNewRepoName('');

      // Apply README template
      try {
        const savedTemplate = localStorage.getItem('gitdeploy_readme_template') || `<!-- Repo Generated by Github Deploy -->\n# {REPO_NAME}\n\nThis repository was automatically provisioned.\n\n## Quick Start\n1. Clone the repository\n2. Install dependencies with \`npm install\`\n3. Start the dev server with \`npm run dev\`\n\n## Deployment Link\n<!-- DEPLOY_LINK_START -->\nNo active deployments yet.\n<!-- DEPLOY_LINK_END -->\n`;
        const content = savedTemplate.replace(/{REPO_NAME}/g, repo.name);
        
        // Try to get existing README.md sha if auto_init created it
        let sha;
        try {
          const tree = await getRepoTree(tokens.github, repo.full_name);
          const readme = tree.find(f => f.path.toLowerCase() === 'readme.md');
          if (readme) sha = readme.sha;
        } catch(e) {}
        
        await createOrUpdateFile(
          tokens.github, 
          repo.full_name, 
          'README.md', 
          content, 
          'Initial commit: Add README.md from template',
          sha
        );
      } catch (templateErr) {
        console.error('Failed to apply template:', templateErr);
      }
    } catch (err: any) {
      alert(`Failed to create repo: ${err.message}`);
    } finally {
      setCreatingRepo(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 flex flex-col font-sans transition-colors">
      {/* Header */}
      <header className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800 px-6 py-3 flex items-center justify-between sticky top-0 z-50">
        <div className="relative">
          <div 
            className="flex items-center gap-3 cursor-pointer select-none group"
            onClick={() => setShowMenu(!showMenu)}
          >
            <div className="bg-black text-white p-1.5 rounded-lg group-hover:bg-gray-800 transition-colors">
              <LayoutGrid size={20} />
            </div>
            <h1 className="font-semibold text-gray-900 dark:text-white tracking-tight">Github Deploy</h1>
          </div>
          
          {showMenu && (
            <div className="absolute top-full left-0 mt-2 w-56 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-lg py-1 z-50">
              <button 
                onClick={() => { setCurrentView('dashboard'); setShowMenu(false); }}
                className={`w-full text-left px-4 py-2 text-sm flex items-center gap-2 hover:bg-gray-50 dark:hover:bg-gray-700 ${currentView === 'dashboard' ? 'text-blue-600 dark:text-blue-400 font-medium' : 'text-gray-700 dark:text-gray-300'}`}
              >
                <LayoutGrid size={16} /> Dashboard
              </button>
              <button 
                onClick={() => { setCurrentView('my-applications'); setShowMenu(false); }}
                className={`w-full text-left px-4 py-2 text-sm flex items-center gap-2 hover:bg-gray-50 dark:hover:bg-gray-700 ${currentView === 'my-applications' ? 'text-blue-600 dark:text-blue-400 font-medium' : 'text-gray-700 dark:text-gray-300'}`}
              >
                <MonitorSmartphone size={16} /> My Applications
              </button>
              <button 
                onClick={() => { setCurrentView('readme-template'); setShowMenu(false); }}
                className={`w-full text-left px-4 py-2 text-sm flex items-center gap-2 hover:bg-gray-50 dark:hover:bg-gray-700 ${currentView === 'readme-template' ? 'text-blue-600 dark:text-blue-400 font-medium' : 'text-gray-700 dark:text-gray-300'}`}
              >
                <FileText size={16} /> README Template
              </button>
              <button 
                onClick={() => { setCurrentView('maintenance'); setShowMenu(false); }}
                className={`w-full text-left px-4 py-2 text-sm flex items-center gap-2 hover:bg-gray-50 dark:hover:bg-gray-700 ${currentView === 'maintenance' ? 'text-blue-600 dark:text-blue-400 font-medium' : 'text-gray-700 dark:text-gray-300'}`}
              >
                <Wrench size={16} /> Maintenance & Repair
              </button>
            </div>
          )}
        </div>
        
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 text-sm">
            <div className={`w-2 h-2 rounded-full ${tokens.github ? 'bg-green-500' : 'bg-red-500'}`} />
            <span className="text-gray-600 dark:text-gray-400">GitHub</span>
            
            <div className={`w-2 h-2 rounded-full ml-2 ${tokens.vercel ? 'bg-green-500' : 'bg-red-500'}`} />
            <span className="text-gray-600 dark:text-gray-400">Vercel</span>
          </div>
          
          <button 
            onClick={() => setDarkMode(!darkMode)}
            className="p-2 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-full transition-colors"
          >
            {darkMode ? <Sun size={20} /> : <Moon size={20} />}
          </button>

          <button 
            onClick={() => setShowTokens(true)}
            className="p-2 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-full transition-colors"
          >
            <Settings size={20} />
          </button>
        </div>
      </header>

      <main className="flex-1 max-w-7xl w-full mx-auto p-6 dark:bg-gray-950 transition-colors">
        {currentView === 'dashboard' ? (
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            {/* Sidebar - Repo Selection */}
            <div className="lg:col-span-1 space-y-6">
              <div className="bg-white dark:bg-gray-900 p-4 rounded-xl shadow-sm border border-gray-200 dark:border-gray-800">
                <h2 className="font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                  <Github size={18} /> Select Repository
                </h2>
                
                {!tokens.github ? (
                  <div className="text-sm text-gray-500 dark:text-gray-400 text-center py-4">
                    Please add GitHub token in settings.
                  </div>
                ) : repoError ? (
                  <div className="text-sm text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 border border-red-100 dark:border-red-800 p-3 rounded-lg text-center">
                    {repoError}
                  </div>
                ) : (
                  <div className="space-y-4">
                    <select 
                      value={selectedRepo}
                      onChange={e => setSelectedRepo(e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg outline-none focus:ring-2 focus:ring-blue-500 text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                    >
                      <option value="">-- Select a Repository --</option>
                      {repos.map(r => (
                        <option key={r.id} value={r.full_name}>{r.full_name}</option>
                      ))}
                    </select>

                    <div className="relative flex items-center py-2">
                      <div className="flex-grow border-t border-gray-200 dark:border-gray-700"></div>
                      <span className="flex-shrink-0 mx-4 text-gray-400 text-xs uppercase tracking-wider">Or</span>
                      <div className="flex-grow border-t border-gray-200 dark:border-gray-700"></div>
                    </div>

                    <form onSubmit={handleCreateRepo} className="flex gap-2">
                      <input 
                        type="text" 
                        placeholder="New repo name" 
                        value={newRepoName}
                        onChange={e => setNewRepoName(e.target.value)}
                        className="flex-1 px-3 py-1.5 border border-gray-300 dark:border-gray-700 rounded-md outline-none focus:border-blue-500 text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                      />
                      <button 
                        type="submit"
                        disabled={creatingRepo || !newRepoName}
                        className="bg-gray-900 dark:bg-white hover:bg-black dark:hover:bg-gray-200 disabled:bg-gray-400 dark:disabled:bg-gray-600 text-white dark:text-black p-1.5 rounded-md transition-colors"
                      >
                        <Plus size={18} />
                      </button>
                    </form>
                  </div>
                )}
              </div>
              
              <div className="bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-300 p-4 rounded-xl text-sm leading-relaxed border border-blue-100 dark:border-blue-800/30">
                <p className="font-medium mb-1">Workflow:</p>
                <ol className="list-decimal pl-4 space-y-1 text-blue-700/90 dark:text-blue-300/90">
                  <li>Select or create a GitHub repo.</li>
                  <li>Upload a ZIP file to extract to the repo.</li>
                  <li>Link Vercel to auto-deploy on push.</li>
                  <li>Upload APK to share releases.</li>
                </ol>
              </div>
            </div>

            {/* Dashboards */}
            <div className="lg:col-span-3 space-y-6">
              {!selectedRepo ? (
                <div className="h-64 flex flex-col items-center justify-center text-gray-400 dark:text-gray-500 border-2 border-dashed border-gray-200 dark:border-gray-800 rounded-xl bg-white dark:bg-gray-900">
                  <Github size={48} className="mb-4 text-gray-300 dark:text-gray-600" />
                  <p className="text-gray-900 dark:text-white font-medium">No Repository Selected</p>
                  <p className="text-sm">Select a repository from the sidebar to continue.</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="md:col-span-2">
                    <FileExplorer tokens={tokens} repoFullName={selectedRepo} />
                  </div>
                  <div>
                    <DeployManager tokens={tokens} repoFullName={selectedRepo} />
                  </div>
                  <div>
                    <ReleaseManager tokens={tokens} repoFullName={selectedRepo} />
                  </div>
                </div>
              )}
            </div>
          </div>
        ) : currentView === 'my-applications' ? (
          <MyApplicationsPage 
            tokens={tokens}
            repos={repos} 
            onSelectRepo={(repoName) => {
              setSelectedRepo(repoName);
              setCurrentView('dashboard');
            }} 
          />
        ) : currentView === 'readme-template' ? (
          <ReadmeTemplatePage />
        ) : (
          <MaintenancePage tokens={tokens} repos={repos} onRepoDeleted={() => {
            // refresh repos
            getUserRepos(tokens.github).then(setRepos).catch(console.error);
          }} />
        )}
      </main>

      {/* Settings Modal */}
      {showTokens && (
        <TokenManager 
          tokens={tokens} 
          setTokens={setTokens} 
          onClose={() => setShowTokens(false)} 
        />
      )}
      
      {/* Click outside to close menu overlay */}
      {showMenu && (
        <div 
          className="fixed inset-0 z-40"
          onClick={() => setShowMenu(false)}
        />
      )}
    </div>
  );
}
